[build]
builder = "nixpacks"

[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python312", "ffmpeg", "opus"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "pip install -U yt-dlp"
]

[start]
cmd = "python main.py"
